#!/usr/bin/env bash

dir="$(dirname "${BASH_SOURCE[0]}")"
source "$dir"/.spark-rc

parse_spark_helper_args "$@"

if [ -n "$sh_version" ]; then
  if [ ! -d "$sh_spark_dir" ]; then
    echo "Fetching released version: $sh_version"
    tgz="$(basename "$sh_spark_dir").tgz"
    local_tgz="$sparks/$tgz"
    url="${SPARK_MIRROR:-http://www.motorlogy.com/apache}/spark/spark-${sh_version}/${tgz}"
    echo "$sh_spark_dir not found; fetching $url"
    wget "$url" -O "$local_tgz"
    tar xvzf "$local_tgz" -C "$sparks"
  fi
else
  if ! spark-build; then
    return 1
  fi
fi

export SPARK_HOME="$sh_spark_dir"

sh_sha=
sh_hadoop_version=
sh_clean_arg=
sh_hadoop_args=
sh_version=
sh_spark_dir=
