#!/usr/bin/env bash

port="${1:-18080}"
dir="${2:-$SPARK_EVENTLOG_DIR}"
num="${3:-5000}"

export SPARK_HISTORY_OPTS="-Dspark.history.ui.port=$port -Dspark.history.fs.logDirectory=$dir -Dspark.history.retainedApplications=$num"

echo "$SPARK_HISTORY_OPTS"
