#!/usr/bin/env bash

# Clone a given Spark SHA and hadoop version into $sparks.
# This script is typically `source`d (e.g. by `spark-build`) so that it can
# change the working directory.

if [ -z "$sh_sha" ]; then

  if [ $# -eq 0 ]; then
    echo "Usage: $0 <sha> <hadoop version>" 1>&2
    return 1
  fi

  dir="$(dirname "${BASH_SOURCE[0]}")"
  source "$dir"/.spark-rc

  echo "clone parsing"
  parse_spark_helper_args "$@"
fi

if [ -d "$sh_spark_dir" ]; then
  echo "Found dir $sh_spark_dir"
else
  echo "Cloning spark into $sh_spark_dir"
  git clone "${SPARK_REPO_URL:-git@github.com:apache/spark.git}" "$sh_spark_dir"
fi
cd "$sh_spark_dir"
git checkout "$sh_sha"
